server:
  port: 8001
spring:
  application:
    name: admin-server
  mail:
    host: smtp.qq.com
    username: 582748391@qq.com
    password: rukabin8081
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          to: 582748391@qq.com # 发送给谁
          from: 582748391@qq.com # 是谁发送出去的
    
    
eureka:
  instance:
      hostname: 192.168.32.140
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://192.168.32.140:8761/eureka/    # 指定注册中心的地址
management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到
info:
  version: 0.0.2
